version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: cnav_db
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes' # Or use a dummy password
      MYSQL_ROOT_HOST: "%"

    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: